/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizzyBee.Registstion;

import com.formdev.flatlaf.FlatDarkLaf;

/**
 *
 * @author USER
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public signUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pictureBox2 = new QuizzyBee.SwingResources.PictureBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pictureBox1 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox3 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox6 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox7 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox8 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox9 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox10 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox11 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox12 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox13 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox14 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox15 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox16 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox17 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox18 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox19 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox20 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox21 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox22 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox23 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox24 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox25 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox26 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox27 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox28 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox29 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox30 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox31 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox32 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox33 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox34 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox35 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox36 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox37 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox38 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox39 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox40 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox41 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox42 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox43 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox44 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox45 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox46 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox47 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox48 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox49 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox50 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox51 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox52 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox53 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox54 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox55 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox56 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox57 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox58 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox59 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox60 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox61 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox62 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox63 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox64 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox65 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox66 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox67 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox68 = new QuizzyBee.SwingResources.PictureBox();
        pictureBox4 = new QuizzyBee.SwingResources.PictureBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pictureBox5 = new QuizzyBee.SwingResources.PictureBox();
        jPasswordField2 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Term of Use | Privacy Policy ");
        jLabel2.setPreferredSize(new java.awt.Dimension(479, 20));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 830, 990, 30));

        pictureBox2.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/Black_Yellow_Modern_World_Bee_Day__Poster___1_-removebg-preview.png"))); // NOI18N
        pictureBox2.setPreferredSize(new java.awt.Dimension(420, 600));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your Name");
        jLabel3.setPreferredSize(new java.awt.Dimension(479, 20));
        pictureBox2.add(jLabel3);
        jLabel3.setBounds(210, 320, 580, 16);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(250, 203, 27));
        jLabel5.setText("Your Name Beautiful");
        pictureBox2.add(jLabel5);
        jLabel5.setBounds(210, 380, 580, 16);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Re-Enter Password");
        jLabel6.setPreferredSize(new java.awt.Dimension(479, 20));
        pictureBox2.add(jLabel6);
        jLabel6.setBounds(210, 500, 580, 16);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");
        jLabel10.setPreferredSize(new java.awt.Dimension(479, 20));
        pictureBox2.add(jLabel10);
        jLabel10.setBounds(210, 230, 580, 16);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setForeground(new java.awt.Color(250, 203, 27));
        jLabel11.setText("Perfect !");
        pictureBox2.add(jLabel11);
        jLabel11.setBounds(210, 290, 580, 16);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(250, 203, 27));
        jLabel8.setText("Your Password is Str\\ong !");
        pictureBox2.add(jLabel8);
        jLabel8.setBounds(210, 470, 580, 16);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password");
        jLabel13.setPreferredSize(new java.awt.Dimension(479, 20));
        pictureBox2.add(jLabel13);
        jLabel13.setBounds(210, 410, 580, 16);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(250, 203, 27));
        jLabel4.setText("Your Password is Str\\ong !");
        pictureBox2.add(jLabel4);
        jLabel4.setBounds(210, 570, 580, 16);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(250, 203, 27));
        jTextField1.setBorder(null);
        pictureBox2.add(jTextField1);
        jTextField1.setBounds(210, 340, 580, 30);

        jPanel1.add(pictureBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 592));

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/Black_Yellow_Modern_World_Bee_Day__Poster___2_-removebg-preview.png"))); // NOI18N
        pictureBox1.setPreferredSize(new java.awt.Dimension(420, 600));

        pictureBox3.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox6.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox3.add(pictureBox6);
        pictureBox6.setBounds(180, 440, 30, 30);

        pictureBox7.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox8.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox7.add(pictureBox8);
        pictureBox8.setBounds(180, 440, 30, 30);

        pictureBox3.add(pictureBox7);
        pictureBox7.setBounds(180, 440, 30, 30);

        pictureBox9.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox10.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox9.add(pictureBox10);
        pictureBox10.setBounds(180, 440, 30, 30);

        pictureBox11.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox12.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox11.add(pictureBox12);
        pictureBox12.setBounds(180, 440, 30, 30);

        pictureBox9.add(pictureBox11);
        pictureBox11.setBounds(180, 440, 30, 30);

        pictureBox3.add(pictureBox9);
        pictureBox9.setBounds(180, 550, 30, 30);

        pictureBox13.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox14.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox13.add(pictureBox14);
        pictureBox14.setBounds(180, 440, 30, 30);

        pictureBox15.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox16.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox15.add(pictureBox16);
        pictureBox16.setBounds(180, 440, 30, 30);

        pictureBox13.add(pictureBox15);
        pictureBox15.setBounds(180, 440, 30, 30);

        pictureBox17.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox18.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox17.add(pictureBox18);
        pictureBox18.setBounds(180, 440, 30, 30);

        pictureBox19.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox20.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox19.add(pictureBox20);
        pictureBox20.setBounds(180, 440, 30, 30);

        pictureBox17.add(pictureBox19);
        pictureBox19.setBounds(180, 440, 30, 30);

        pictureBox13.add(pictureBox17);
        pictureBox17.setBounds(180, 550, 30, 30);

        pictureBox3.add(pictureBox13);
        pictureBox13.setBounds(180, 550, 30, 30);

        pictureBox21.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox22.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox21.add(pictureBox22);
        pictureBox22.setBounds(180, 440, 30, 30);

        pictureBox23.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox24.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox23.add(pictureBox24);
        pictureBox24.setBounds(180, 440, 30, 30);

        pictureBox21.add(pictureBox23);
        pictureBox23.setBounds(180, 440, 30, 30);

        pictureBox25.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox26.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox25.add(pictureBox26);
        pictureBox26.setBounds(180, 440, 30, 30);

        pictureBox27.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox28.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox27.add(pictureBox28);
        pictureBox28.setBounds(180, 440, 30, 30);

        pictureBox25.add(pictureBox27);
        pictureBox27.setBounds(180, 440, 30, 30);

        pictureBox21.add(pictureBox25);
        pictureBox25.setBounds(180, 550, 30, 30);

        pictureBox29.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox30.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox29.add(pictureBox30);
        pictureBox30.setBounds(180, 440, 30, 30);

        pictureBox31.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox32.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox31.add(pictureBox32);
        pictureBox32.setBounds(180, 440, 30, 30);

        pictureBox29.add(pictureBox31);
        pictureBox31.setBounds(180, 440, 30, 30);

        pictureBox33.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox34.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox33.add(pictureBox34);
        pictureBox34.setBounds(180, 440, 30, 30);

        pictureBox35.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox36.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox35.add(pictureBox36);
        pictureBox36.setBounds(180, 440, 30, 30);

        pictureBox33.add(pictureBox35);
        pictureBox35.setBounds(180, 440, 30, 30);

        pictureBox29.add(pictureBox33);
        pictureBox33.setBounds(180, 550, 30, 30);

        pictureBox21.add(pictureBox29);
        pictureBox29.setBounds(180, 550, 30, 30);

        pictureBox3.add(pictureBox21);
        pictureBox21.setBounds(180, 550, 30, 30);

        pictureBox1.add(pictureBox3);
        pictureBox3.setBounds(180, 430, 30, 30);

        pictureBox37.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox38.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox37.add(pictureBox38);
        pictureBox38.setBounds(180, 440, 30, 30);

        pictureBox39.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox40.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox39.add(pictureBox40);
        pictureBox40.setBounds(180, 440, 30, 30);

        pictureBox37.add(pictureBox39);
        pictureBox39.setBounds(180, 440, 30, 30);

        pictureBox41.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox42.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox41.add(pictureBox42);
        pictureBox42.setBounds(180, 440, 30, 30);

        pictureBox43.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox44.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox43.add(pictureBox44);
        pictureBox44.setBounds(180, 440, 30, 30);

        pictureBox41.add(pictureBox43);
        pictureBox43.setBounds(180, 440, 30, 30);

        pictureBox37.add(pictureBox41);
        pictureBox41.setBounds(180, 550, 30, 30);

        pictureBox45.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox46.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox45.add(pictureBox46);
        pictureBox46.setBounds(180, 440, 30, 30);

        pictureBox47.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox48.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox47.add(pictureBox48);
        pictureBox48.setBounds(180, 440, 30, 30);

        pictureBox45.add(pictureBox47);
        pictureBox47.setBounds(180, 440, 30, 30);

        pictureBox49.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox50.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox49.add(pictureBox50);
        pictureBox50.setBounds(180, 440, 30, 30);

        pictureBox51.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox52.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox51.add(pictureBox52);
        pictureBox52.setBounds(180, 440, 30, 30);

        pictureBox49.add(pictureBox51);
        pictureBox51.setBounds(180, 440, 30, 30);

        pictureBox45.add(pictureBox49);
        pictureBox49.setBounds(180, 550, 30, 30);

        pictureBox37.add(pictureBox45);
        pictureBox45.setBounds(180, 550, 30, 30);

        pictureBox53.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox54.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox53.add(pictureBox54);
        pictureBox54.setBounds(180, 440, 30, 30);

        pictureBox55.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox56.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox55.add(pictureBox56);
        pictureBox56.setBounds(180, 440, 30, 30);

        pictureBox53.add(pictureBox55);
        pictureBox55.setBounds(180, 440, 30, 30);

        pictureBox57.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox58.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox57.add(pictureBox58);
        pictureBox58.setBounds(180, 440, 30, 30);

        pictureBox59.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox60.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox59.add(pictureBox60);
        pictureBox60.setBounds(180, 440, 30, 30);

        pictureBox57.add(pictureBox59);
        pictureBox59.setBounds(180, 440, 30, 30);

        pictureBox53.add(pictureBox57);
        pictureBox57.setBounds(180, 550, 30, 30);

        pictureBox61.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox62.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox61.add(pictureBox62);
        pictureBox62.setBounds(180, 440, 30, 30);

        pictureBox63.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox64.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox63.add(pictureBox64);
        pictureBox64.setBounds(180, 440, 30, 30);

        pictureBox61.add(pictureBox63);
        pictureBox63.setBounds(180, 440, 30, 30);

        pictureBox65.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox66.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox65.add(pictureBox66);
        pictureBox66.setBounds(180, 440, 30, 30);

        pictureBox67.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N

        pictureBox68.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        pictureBox67.add(pictureBox68);
        pictureBox68.setBounds(180, 440, 30, 30);

        pictureBox65.add(pictureBox67);
        pictureBox67.setBounds(180, 440, 30, 30);

        pictureBox61.add(pictureBox65);
        pictureBox65.setBounds(180, 550, 30, 30);

        pictureBox53.add(pictureBox61);
        pictureBox61.setBounds(180, 550, 30, 30);

        pictureBox37.add(pictureBox53);
        pictureBox53.setBounds(180, 550, 30, 30);

        pictureBox1.add(pictureBox37);
        pictureBox37.setBounds(180, 530, 30, 30);

        jPanel1.add(pictureBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 420, 599));

        pictureBox4.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/Quizzy_Bee__2_-removebg-preview.png"))); // NOI18N
        jPanel1.add(pictureBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 290, 120));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME BACK");
        jLabel1.setPreferredSize(new java.awt.Dimension(139, 31));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 270, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 580, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 580, 10));

        jButton1.setBackground(new java.awt.Color(250, 203, 27));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign In");
        jButton1.setPreferredSize(new java.awt.Dimension(397, 47));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 740, 440, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Forget My Password | Allready Registered?");
        jLabel7.setPreferredSize(new java.awt.Dimension(479, 20));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 790, 990, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 580, 10));

        pictureBox5.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-20.png"))); // NOI18N
        jPanel1.add(pictureBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jPasswordField2.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(250, 203, 27));
        jPasswordField2.setBorder(null);
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 540, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 580, 10));

        jPasswordField3.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPasswordField3.setForeground(new java.awt.Color(250, 203, 27));
        jPasswordField3.setBorder(null);
        jPasswordField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 540, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        jLabel12.setPreferredSize(new java.awt.Dimension(479, 20));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 580, 16));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 203, 27), 3));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setText("Male");
        jPanel11.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel22.setText("jLabel9");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setText("Male");
        jPanel12.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel23.setText("jLabel9");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setText("Male");
        jPanel13.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel24.setText("jLabel9");
        jPanel13.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 3));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jButton15.setForeground(new java.awt.Color(250, 203, 27));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-male-32.png"))); // NOI18N
        jButton15.setText("Male");
        jButton15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel14.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton16.setText("Male");
        jPanel15.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel26.setText("jLabel9");
        jPanel15.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setText("Male");
        jPanel16.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel27.setText("jLabel9");
        jPanel16.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton18.setText("Male");
        jPanel17.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel28.setText("jLabel9");
        jPanel17.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel14.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel10.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 70));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-female-32.png"))); // NOI18N
        jButton10.setText("Female");
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel10.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 210, 70));

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 203, 27), 3));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-male-32.png"))); // NOI18N
        jButton19.setText(" Male    ");
        jButton19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton20.setText("Male");
        jPanel19.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel29.setText("jLabel9");
        jPanel19.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton21.setText("Male");
        jPanel20.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel30.setText("jLabel9");
        jPanel20.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.setText("Male");
        jPanel21.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel31.setText("jLabel9");
        jPanel21.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel22.setBackground(new java.awt.Color(0, 0, 0));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 3));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton23.setBackground(new java.awt.Color(0, 0, 0));
        jButton23.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jButton23.setForeground(new java.awt.Color(250, 203, 27));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-male-32.png"))); // NOI18N
        jButton23.setText("Male");
        jButton23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel22.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton24.setText("Male");
        jPanel23.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel32.setText("jLabel9");
        jPanel23.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton25.setText("Male");
        jPanel24.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel33.setText("jLabel9");
        jPanel24.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton26.setText("Male");
        jPanel25.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 164, 50));

        jLabel34.setText("jLabel9");
        jPanel25.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 0, 40, 50));

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel22.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 50));

        jPanel18.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 210, 70));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 210, 70));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(250, 203, 27));
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 580, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField3ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private QuizzyBee.SwingResources.PictureBox pictureBox1;
    private QuizzyBee.SwingResources.PictureBox pictureBox10;
    private QuizzyBee.SwingResources.PictureBox pictureBox11;
    private QuizzyBee.SwingResources.PictureBox pictureBox12;
    private QuizzyBee.SwingResources.PictureBox pictureBox13;
    private QuizzyBee.SwingResources.PictureBox pictureBox14;
    private QuizzyBee.SwingResources.PictureBox pictureBox15;
    private QuizzyBee.SwingResources.PictureBox pictureBox16;
    private QuizzyBee.SwingResources.PictureBox pictureBox17;
    private QuizzyBee.SwingResources.PictureBox pictureBox18;
    private QuizzyBee.SwingResources.PictureBox pictureBox19;
    private QuizzyBee.SwingResources.PictureBox pictureBox2;
    private QuizzyBee.SwingResources.PictureBox pictureBox20;
    private QuizzyBee.SwingResources.PictureBox pictureBox21;
    private QuizzyBee.SwingResources.PictureBox pictureBox22;
    private QuizzyBee.SwingResources.PictureBox pictureBox23;
    private QuizzyBee.SwingResources.PictureBox pictureBox24;
    private QuizzyBee.SwingResources.PictureBox pictureBox25;
    private QuizzyBee.SwingResources.PictureBox pictureBox26;
    private QuizzyBee.SwingResources.PictureBox pictureBox27;
    private QuizzyBee.SwingResources.PictureBox pictureBox28;
    private QuizzyBee.SwingResources.PictureBox pictureBox29;
    private QuizzyBee.SwingResources.PictureBox pictureBox3;
    private QuizzyBee.SwingResources.PictureBox pictureBox30;
    private QuizzyBee.SwingResources.PictureBox pictureBox31;
    private QuizzyBee.SwingResources.PictureBox pictureBox32;
    private QuizzyBee.SwingResources.PictureBox pictureBox33;
    private QuizzyBee.SwingResources.PictureBox pictureBox34;
    private QuizzyBee.SwingResources.PictureBox pictureBox35;
    private QuizzyBee.SwingResources.PictureBox pictureBox36;
    private QuizzyBee.SwingResources.PictureBox pictureBox37;
    private QuizzyBee.SwingResources.PictureBox pictureBox38;
    private QuizzyBee.SwingResources.PictureBox pictureBox39;
    private QuizzyBee.SwingResources.PictureBox pictureBox4;
    private QuizzyBee.SwingResources.PictureBox pictureBox40;
    private QuizzyBee.SwingResources.PictureBox pictureBox41;
    private QuizzyBee.SwingResources.PictureBox pictureBox42;
    private QuizzyBee.SwingResources.PictureBox pictureBox43;
    private QuizzyBee.SwingResources.PictureBox pictureBox44;
    private QuizzyBee.SwingResources.PictureBox pictureBox45;
    private QuizzyBee.SwingResources.PictureBox pictureBox46;
    private QuizzyBee.SwingResources.PictureBox pictureBox47;
    private QuizzyBee.SwingResources.PictureBox pictureBox48;
    private QuizzyBee.SwingResources.PictureBox pictureBox49;
    private QuizzyBee.SwingResources.PictureBox pictureBox5;
    private QuizzyBee.SwingResources.PictureBox pictureBox50;
    private QuizzyBee.SwingResources.PictureBox pictureBox51;
    private QuizzyBee.SwingResources.PictureBox pictureBox52;
    private QuizzyBee.SwingResources.PictureBox pictureBox53;
    private QuizzyBee.SwingResources.PictureBox pictureBox54;
    private QuizzyBee.SwingResources.PictureBox pictureBox55;
    private QuizzyBee.SwingResources.PictureBox pictureBox56;
    private QuizzyBee.SwingResources.PictureBox pictureBox57;
    private QuizzyBee.SwingResources.PictureBox pictureBox58;
    private QuizzyBee.SwingResources.PictureBox pictureBox59;
    private QuizzyBee.SwingResources.PictureBox pictureBox6;
    private QuizzyBee.SwingResources.PictureBox pictureBox60;
    private QuizzyBee.SwingResources.PictureBox pictureBox61;
    private QuizzyBee.SwingResources.PictureBox pictureBox62;
    private QuizzyBee.SwingResources.PictureBox pictureBox63;
    private QuizzyBee.SwingResources.PictureBox pictureBox64;
    private QuizzyBee.SwingResources.PictureBox pictureBox65;
    private QuizzyBee.SwingResources.PictureBox pictureBox66;
    private QuizzyBee.SwingResources.PictureBox pictureBox67;
    private QuizzyBee.SwingResources.PictureBox pictureBox68;
    private QuizzyBee.SwingResources.PictureBox pictureBox7;
    private QuizzyBee.SwingResources.PictureBox pictureBox8;
    private QuizzyBee.SwingResources.PictureBox pictureBox9;
    // End of variables declaration//GEN-END:variables
}
